export abstract class Utils {
  public static getFileType(
    fileExtension: string
  ): 'document' | 'image' | 'archive' | 'audio' | 'video' | 'file' | 'executable' | 'other' {
    const typeMap = {
      document: [
        'pdf',
        'doc',
        'docx',
        'txt',
        'rtf',
        'odt',
        'xls',
        'xlsx',
        'csv',
        'ppt',
        'pptx',
        'odp',
        'ods',
        'md',
        'pages',
        'numbers',
        'tex',
        'epub',
        'mobi',
        'ott',
        'pptm',
        'xlsm',
      ],
      image: [
        'jpg',
        'jpeg',
        'png',
        'gif',
        'bmp',
        'svg',
        'webp',
        'tiff',
        'tif',
        'ico',
        'psd',
        'ai',
        'heic',
        'heif',
        'avif',
        'jxl',
        'eps',
        'raw',
        'cr2',
        'nef',
        'dng',
        'arw',
        'exr',
        'hdr',
        'jfif',
        'jpe',
        'jp2',
        'pcx',
        'tga',
      ],
      archive: [
        'zip',
        'rar',
        '7z',
        'tar',
        'gz',
        'bz2',
        'xz',
        'iso',
        'dmg',
        'zst',
        'cab',
        'tgz',
        'lz',
        'lzma',
      ],
      audio: [
        'mp3',
        'wav',
        'ogg',
        'flac',
        'aac',
        'm4a',
        'wma',
        'aiff',
        'opus',
        'mid',
        'midi',
        'ape',
        'amr',
        'ac3',
        'dts',
        'mp2',
        'au',
        'caf',
        'alac',
      ],
      video: [
        'mp4',
        'mov',
        'avi',
        'mkv',
        'wmv',
        'flv',
        'webm',
        'm4v',
        'mpg',
        'mpeg',
        '3gp',
        '3g2',
        'ogv',
        'mxf',
        'ts',
        'vob',
      ],
      file: [
        'json',
        'xml',
        'yaml',
        'toml',
        'ini',
        'cfg',
        'conf',
        'log',
        'sql',
        'dat',
        'html',
        'htm',
        'css',
      ],
      executable: [
        'exe',
        'msi',
        'app',
        'sh',
        'bat',
        'cmd',
        'com',
        'gadget',
        'jar',
        'py',
        'js',
        'deb',
        'rpm',
        'pkg',
        'apk',
        'appimage',
        'snap',
        'flatpak',
        'ipa',
        'run',
        'bin',
      ],
    };

    for (const [type, extensions] of Object.entries(typeMap) as [
      keyof typeof typeMap,
      string[],
    ][]) {
      if (extensions.includes(fileExtension)) {
        return type;
      }
    }

    return 'other';
  }
}
